### ISSUE TITLE
Java bindings on OBS mostly fail

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusBindings#17]
This is mainly due to probing the correct Java JDK version and probing various 
aspects of Java (JNI, MAWT, etc). This needs some work. This also doesn't mean
the Java Bindings are generally broken, they are just broken in the OBS builds.

**Comment by andreasbaumann** [comment]
In detail:
- java SDK not found on most platforms: Centos 5/6, Debian 7, Ubuntu 12.04, Fedora 22
  and 23.
- some platforms still have Java 7 and not 8, we should triage on that.
- some Debianish systems have problems to find and link against a working `libmawt.so`
  library

**Comment by patrickfrey** [comment]
Java JNI bindings do not exist anymore
