### ISSUE TITLE
Build fails on Archlinux due to missing zend_config.nw.h header file

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusBindings#50]
php version on Archlinux is 7.4.0.

```
[ 82%] Building C object strusBindings/3rdParty/papuga/php7/CMakeFiles/papuga_php7_dev.dir/libpapuga_php7_dev.c.o
strusAll/strusBindings/3rdParty/papuga/php7/libpapuga_php7_dev.c:29:10: fatal error: zend_config.nw.h: No such file or directory
   29 | #include <zend_config.nw.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [strusBindings/3rdParty/papuga/php7/CMakeFiles/papuga_php7_dev.dir/build.make:63: strusBindings/3rdParty/papuga/php7/CMakeFiles/papuga_php7_dev.dir/libpapuga_php7_dev.c.o] Error 1
```

config.nw.h is either a Debian/Ubuntu only thing or it is a php 5 thing and got dropped with php 7.

I'm not sure what zend_portability.h is doing, but it looks it is part of a portability layer doing
the correct includes.

Chaging zend_config.nw.h manually to zend_config.h made my build succeed, all tests passed.

**Comment by patrickfrey** [comment]
Include removed, probably a leftover of bindings to PHP 5.x
